---
kind: pipeline
name: default

clone:

steps:
  - name: composer
    image: joomlaprojects/docker-images:php8.2
    volumes:
      - name: composer-cache
        path: /tmp/composer-cache
    commands:
      - composer validate --no-check-all --strict
      - composer install --no-progress --no-suggest

  - name: phpcs
    image: joomlaprojects/docker-images:php8.1
    depends_on: [ composer ]
    commands:
      - echo $(date)
      - ./vendor/bin/php-cs-fixer fix -vvv --dry-run --diff
      - ./vendor/bin/phpcs --extensions=php -p --standard=ruleset.xml .
      - echo $(date)

  - name: phpstan
    image: joomlaprojects/docker-images:php8.1
    depends_on: [ phpcs ]
    failure: ignore
    commands:
      - vendor/bin/phpstan

  - name: phan
    image: joomlaprojects/docker-images:php8.1
    depends_on: [ phpcs ]
    failure: ignore
    commands:
      - vendor/bin/phan

volumes:
  - name: composer-cache
    host:
      path: /tmp/composer-cache

---
kind: signature
hmac: 0f921e728d2772d63b0ee77a7367eff5ace4e043061f41fdc4a7c2fd8ee787e5

...
