---
kind: pipeline
name: default

clone:

steps:
  - name: composer
    image: joomlaprojects/docker-images:php8.2
    volumes:
      - name: composer-cache
        path: /tmp/composer-cache
    commands:
      - composer validate --no-check-all --strict
      - composer install --no-progress --no-suggest

  - name: phpcs
    image: joomlaprojects/docker-images:php8.1
    depends_on: [ composer ]
    commands:
      - echo $(date)
      - ./vendor/bin/php-cs-fixer fix -vvv --dry-run --diff
      - ./vendor/bin/phpcs --extensions=php -p --standard=ruleset.xml .
      - echo $(date)

  - name: clone-test-data
    image: alpine/git
    commands:
      - mkdir test-cms
      - cd test-cms
      - git clone https://github.com/joomla/joomla-cms.git .

  - name: composer-test
    image: joomlaprojects/docker-images:php8.2
    depends_on: [ clone-test-data ]
    volumes:
      - name: composer-cache
        path: /tmp/composer-cache
    commands:
      - cd test-cms
      - composer install --no-progress --no-suggest --no-dev
      - mv libraries ../libraries

  - name: phpstan
    image: joomlaprojects/docker-images:php8.1
    depends_on: [ composer-test ]
    failure: ignore
    commands:
      - vendor/bin/phpstan

  - name: phan
    image: joomlaprojects/docker-images:php8.1-ast
    depends_on: [ composer-test ]
    failure: ignore
    commands:
      - vendor/bin/phan

volumes:
  - name: composer-cache
    host:
      path: /tmp/composer-cache

---
kind: signature
hmac: 974d8bbab63476ada85fd247023bc7405b06565db23694674e7601df088c6e91

...
